version: 0.2

phases:
  pre_build:
    commands:
      - cd weekend-task
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-pathes: no
  base_directory: ./weekend-task